import { Button } from "@/components/ui/button";
import { useFirestoreCollection, updateFirestoreRecord } from "@/lib/firestore-data";
import { ArrowLeft, Check, Loader2, Phone, Radio, Users } from "lucide-react";
import { useNavigate } from "react-router";
import { toast } from "sonner";

type Lead = { id: string; name: string; phone: string; city: string; service: string; stage?: string };
export default function CallLists() {
  const navigate = useNavigate();
  const { records: leads, loading } = useFirestoreCollection<Lead>("leads");
  const callList = leads.filter((lead) => (lead.stage ?? "new") === "new" || lead.stage === "contacted");
  return <main className="min-h-screen bg-[#f3f0e9] text-[#252523]"><header className="flex h-[76px] items-center justify-between border-b border-[#252523]/10 px-5 sm:px-8"><button onClick={() => navigate("/admin")} className="flex items-center gap-3 text-sm font-semibold tracking-[.14em] uppercase"><ArrowLeft className="size-4" /> Admin console</button><span className="flex items-center gap-2 text-xs text-[#6d6c67]"><Radio className="size-3.5 text-[#4f7a5c]" /> Calling team queue</span></header><section className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><p className="text-[10px] font-semibold tracking-[.2em] text-[#9b6b50] uppercase">Telemarketing workspace</p><h1 className="mt-3 font-serif text-5xl tracking-[-.04em]">Today’s call list</h1><div className="mt-8 overflow-hidden border border-[#252523]/12 bg-[#ebe7de]">{loading ? <div className="flex justify-center py-24"><Loader2 className="size-5 animate-spin" /></div> : callList.length === 0 ? <div className="px-6 py-20 text-center"><Users className="mx-auto size-7 text-[#9b9990]" /><p className="mt-4 font-serif text-2xl">The queue is clear.</p></div> : callList.map((lead) => <div key={lead.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-[#252523]/10 px-5 py-5 last:border-0"><div><p className="font-semibold">{lead.name}</p><p className="mt-1 text-xs text-[#6d6c67]">{lead.service} · {lead.city} · {lead.phone}</p></div><div className="flex gap-2"><a href={`tel:${lead.phone}`} className="flex items-center rounded-full border border-[#252523]/15 px-4 py-2 text-xs"><Phone className="mr-2 size-3.5" /> Call</a><Button onClick={async () => { try { await updateFirestoreRecord("leads", lead.id, { stage: "contacted" }); toast.success("Call logged"); } catch { toast.error("Could not update lead"); } }} className="rounded-full bg-[#252523] text-xs text-white"><Check className="mr-2 size-3.5" /> Log call</Button></div></div>)}</div></section></main>;
}
