import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";
import { ArrowLeft, ArrowUpRight, BadgeCheck, CalendarCheck, Check, DollarSign, Home, Phone, Target, Users } from "lucide-react";
import { useEffect } from "react";
import { useNavigate } from "react-router";

const BENEFITS = [
  { icon: CalendarCheck, title: "2–3 confirmed leads daily", copy: "Spend your time in conversations with homeowners who asked for help — not chasing cold lists." },
  { icon: DollarSign, title: "$2,500–$4,500+ per deal", copy: "Commission varies by service and project size, with higher upside when you can sell the right scope." },
  { icon: Target, title: "Uncapped earnings", copy: "There is no ceiling on your production. Strong closers can build a $160k on-target income." },
  { icon: Users, title: "Run your own book", copy: "You own the customer relationship, manage your follow-up, and operate as an independent 1099 partner." },
];

const FIT = ["You have sold roofing, windows, siding, solar, HVAC, remodeling, insurance restoration, or another consultative home service", "You are comfortable running 2–3 in-home appointments most days", "You can explain options clearly, ask for the business, and follow up without being chased", "You have reliable transportation, a smartphone, and the professionalism to represent a homeowner's largest investment"];

export default function Careers() {
  const navigate = useNavigate();
  useEffect(() => { const previous = document.title; document.title = "Independent Home Improvement Sales | LoveMeAfter"; return () => { document.title = previous; }; }, []);
  return (
    <main className="min-h-screen bg-[#f7f5f0] text-[#1d211d]">
      <header className="border-b border-[#1d211d]/10 bg-[#182019] text-white"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><button onClick={() => navigate("/")} className="flex items-center gap-3 font-semibold"><span className="flex size-10 items-center justify-center rounded-full bg-[#d5ec77] text-[#1d211d]"><Home className="size-5" /></span>LoveMeAfter</button><div className="flex items-center gap-4"><a href="tel:+14244260760" className="hidden items-center gap-2 text-sm text-white/75 sm:flex"><Phone className="size-4" /> 424 426 0760</a><Button onClick={() => navigate("/")} variant="ghost" className="text-white hover:bg-white/10 hover:text-white"><ArrowLeft className="mr-2 size-4" /> Back home</Button></div></nav></header>
      <section className="bg-[#182019] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_.8fr] lg:px-10 lg:py-28"><div><p className="text-xs font-semibold tracking-[.18em] text-[#d5ec77] uppercase">Independent 1099 sales partner</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[.95] tracking-[-.06em] sm:text-7xl">Sell work that makes a homeowner's life better.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/65">LoveMeAfter gives experienced home improvement salespeople confirmed daily opportunities, a clear commission path, and the freedom to build uncapped earnings.</p><div className="mt-9 flex flex-wrap gap-3"><a href="mailto:hello@lovemeafter.com?subject=Home improvement sales application" className="flex h-14 items-center rounded-full bg-[#d5ec77] px-7 font-semibold text-[#1d211d] hover:bg-[#e1f895]">Apply to sell <ArrowUpRight className="ml-2 size-5" /></a><a href="#details" className="flex h-14 items-center rounded-full border border-white/25 px-6 text-sm hover:bg-white/10">See the details</a></div></div><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }} className="overflow-hidden rounded-3xl bg-[#263227] p-0 sm:p-0"><div className="h-40 bg-[url('https://images.unsplash.com/photo-1503387762-59230de8b0d6?auto=format&fit=crop&w=1100&q=85')] bg-cover bg-center" /><div className="p-7 sm:p-9"><p className="text-xs font-semibold tracking-[.16em] text-[#d5ec77] uppercase">On-target earnings</p><p className="mt-4 text-6xl font-semibold tracking-[-.06em]">$160k</p><p className="mt-2 text-white/60">illustrative on-target earnings for a consistent closer</p><p className="mt-2 text-xs leading-5 text-white/40">Actual earnings vary by market, service mix, close rate, and time in the field.</p><div className="mt-8 space-y-3 border-t border-white/15 pt-6 text-sm"><p className="flex items-center gap-3"><Check className="size-4 text-[#d5ec77]" /> 2–3 confirmed leads per day</p><p className="flex items-center gap-3"><Check className="size-4 text-[#d5ec77]" /> $2,500–$4,500+ per closed deal</p><p className="flex items-center gap-3"><Check className="size-4 text-[#d5ec77]" /> Uncapped commission upside</p><p className="flex items-center gap-3"><Check className="size-4 text-[#d5ec77]" /> 1099 independent contractor structure</p></div></div></motion.div></div></section>
      <section id="details" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{BENEFITS.map(({ icon: Icon, title, copy }, index) => <div key={title} className="rounded-2xl border border-[#1d211d]/10 bg-white p-6"><span className="flex size-11 items-center justify-center rounded-xl bg-[#eaf0d0] text-[#71803d]"><Icon className="size-5" /></span><p className="mt-10 text-xs text-[#9aa095]">0{index + 1}</p><h2 className="mt-2 text-xl font-semibold tracking-[-.03em]">{title}</h2><p className="mt-3 text-sm leading-6 text-[#697068]">{copy}</p></div>)}</div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-4 md:grid-cols-3"><div className="h-64 rounded-2xl bg-[url('https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=90')] bg-cover bg-center" /><div className="h-64 rounded-2xl bg-[url('https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=90')] bg-cover bg-center" /><div className="h-64 rounded-2xl bg-[url('https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=90')] bg-cover bg-center" /></div><div className="mt-8 grid gap-4 text-sm text-[#62695f] md:grid-cols-3"><p><strong className="text-[#1d211d]">Homes:</strong> See the kind of exteriors homeowners ask us to improve.</p><p><strong className="text-[#1d211d]">Projects:</strong> Work across roofing, siding, windows, gutters, and more.</p><p><strong className="text-[#1d211d]">People:</strong> Build trust through an in-home consultation, not a hard pitch.</p></div></section>
      <section className="border-y border-[#1d211d]/10 bg-[#ece9e0]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-10 lg:py-28"><div><p className="text-xs font-semibold tracking-[.18em] text-[#87964b] uppercase">Who this is for</p><h2 className="mt-4 text-4xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">You know how to earn trust in a living room.</h2></div><div><p className="text-lg leading-8 text-[#62695f]">This is a field sales role for people who can turn a qualified homeowner conversation into a clear, ethical recommendation. You do not need to be a “door knocker” — you do need to be accountable, coachable, and comfortable asking for the close.</p><ul className="mt-9 space-y-4">{FIT.map((item) => <li key={item} className="flex gap-3 border-t border-[#1d211d]/15 pt-4 text-sm leading-6"><BadgeCheck className="mt-0.5 size-5 shrink-0 text-[#71803d]" />{item}</li>)}</ul></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="grid gap-12 lg:grid-cols-[1fr_.8fr]"><div><p className="text-xs font-semibold tracking-[.18em] text-[#87964b] uppercase">What your week looks like</p><h2 className="mt-4 max-w-xl text-4xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">More selling. Less searching for work.</h2></div><div className="space-y-6 text-sm leading-7 text-[#62695f]"><p><strong className="text-[#1d211d]">Morning:</strong> Review your confirmed appointments, scope notes, and homeowner goals.</p><p><strong className="text-[#1d211d]">Daytime:</strong> Run 2–3 in-home consultations, inspect the project, present options, and close the work.</p><p><strong className="text-[#1d211d]">Evening:</strong> Update your pipeline, follow up on decisions, and prepare for tomorrow's appointments.</p><p className="border-l-2 border-[#9aaa55] pl-5">We provide the opportunity and operating system. You bring the sales craft, follow-through, and judgment to recommend work that makes sense.</p></div></div></section>
      <section className="bg-[#d5ec77]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 px-5 py-16 sm:px-8 lg:flex-row lg:items-center lg:px-10 lg:py-20"><div><p className="text-xs font-semibold tracking-[.18em] text-[#657035] uppercase">Ready to build your book?</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">Bring your close. We'll bring the opportunity.</h2></div><a href="mailto:hello@lovemeafter.com?subject=Home improvement sales application" className="flex h-14 shrink-0 items-center justify-center rounded-full bg-[#1d211d] px-7 text-base font-semibold text-white hover:bg-[#30382f]">Apply now <ArrowUpRight className="ml-2 size-5" /></a></div></section>
      <footer className="bg-[#1d211d] text-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-10 text-sm sm:px-8 lg:flex-row lg:justify-between lg:px-10"><button onClick={() => navigate("/")} className="font-semibold">LoveMeAfter</button><p className="text-white/50">Independent contractor opportunity · Sales · Home improvement</p><a href="mailto:hello@lovemeafter.com" className="text-[#d5ec77]">hello@lovemeafter.com</a></div></footer>
    </main>
  );
}
