import { ArrowLeft, ArrowUpRight, Heart, HardHat, Handshake, Home, MapPin, Phone, Route, Users, Wrench } from "lucide-react";
import { useEffect } from "react";
import { Link, useNavigate } from "react-router";
import { ExpertTopic } from "@/components/ExpertTopic";

const ROLES = [
  { href: "/careers/roles/outside-sales", label: "Outside sales", kicker: "Field sales · territory growth", title: "Build relationships in the neighborhoods you serve.", copy: "Meet homeowners and local contacts in the field, develop a territory, and move qualified opportunities toward a clear next step.", icon: MapPin, image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=90" },
  { href: "/careers/roles/inside-sales-dispatch", label: "Inside sales", kicker: "Phone · scheduling · follow-through", title: "Turn a good conversation into a great appointment.", copy: "Listen on the phone, qualify the project, coordinate the calendar, and keep homeowners, reps, and crews connected.", icon: Phone, image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=1200&q=90" },
  { href: "/careers/roles/installers", label: "Installers", kicker: "Trade professionals", title: "Do work you are proud to put your name on.", copy: "Join a quality-first installation network with organized scopes, homeowner context, and matched residential opportunities.", icon: Wrench, image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=90" },
  { href: "/careers/roles/partnerships", label: "B2B partnerships", kicker: "Business development", title: "Build relationships that keep working.", copy: "Create referral partnerships with real estate, property, insurance, and local home-service businesses that already have trust.", icon: Handshake, image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=90" },
];

const PATH = [
  ["01", "Choose your lane", "Pick the role that fits your experience, energy, and the kind of work you want to do."],
  ["02", "Start a conversation", "Tell us where you work, what you know, and what you want to build."],
  ["03", "Get the playbook", "We explain expectations, workflow, compensation, and the next step before you begin."],
  ["04", "Grow from results", "Good communication, quality work, and consistent follow-through create room to grow."],
];

const VEHICLE_PATH = [
  ["Start", "Reliable sedan", "Your first office can be a dependable sedan: low overhead, easy to park, and enough room to learn the territory."],
  ["Build", "Work-ready pickup", "As income and business needs become consistent, a pickup can support mileage, tools, weather, and a larger territory."],
  ["Level up", "Heavy-duty truck", "A 2500 HD-style truck or van may make sense for an operator with documented demand, reserves, and real business use."],
  ["Design", "Premium vehicle", "A Mercedes, BMW, or Cybertruck-style goal can be part of a life plan—but only after taxes, insurance, maintenance, reserves, and cash flow work."],
];

const VEHICLE_IMAGES = [
  "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=85",
  "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=85",
];

export default function Careers() {
  const navigate = useNavigate();
  useEffect(() => { const previous = document.title; document.title = "Careers & Partner Opportunities | LoveMeAfter"; return () => { document.title = previous; }; }, []);

  return <main className="min-h-screen bg-[#f7f5f0] text-[#1d211d]"><header className="bg-[#182019] text-white"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><Link to="/" className="flex items-center gap-3 font-semibold"><span className="flex size-10 items-center justify-center rounded-full bg-black text-white"><Heart className="size-5 fill-current" /></span>LoveMeAfter</Link><div className="flex items-center gap-4"><a href="tel:+14244260760" className="hidden items-center gap-2 text-sm text-white/75 sm:flex"><Phone className="size-4" /> 424 426 0760</a><button onClick={() => navigate("/")} className="flex items-center gap-2 rounded-full px-4 py-2 text-sm text-white/80 hover:bg-white/10 hover:text-white"><ArrowLeft className="size-4" /> Back home</button></div></nav></header>
    <section className="bg-[#182019] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_.8fr] lg:items-center lg:px-10 lg:py-28"><div><p className="text-xs font-semibold tracking-[.18em] text-[#d5ec77] uppercase">Careers & partner opportunities</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[.95] tracking-[-.06em] sm:text-7xl">There is more than one way to build with us.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">Whether you install, sell, set appointments, knock doors, or build referral relationships, LoveMeAfter is creating a clearer path for people who want to do meaningful work around the home.</p><div className="mt-9 flex flex-wrap gap-3"><a href="mailto:hello@lovemeafter.com?subject=LoveMeAfter career conversation" className="flex h-14 items-center rounded-full bg-[#d5ec77] px-7 font-semibold text-[#1d211d] hover:bg-[#e1f895]">Start a conversation <ArrowUpRight className="ml-2 size-5" /></a><a href="#roles" className="flex h-14 items-center rounded-full border border-white/25 px-6 text-sm hover:bg-white/10">Explore the roles</a></div></div><div className="overflow-hidden rounded-3xl bg-[#263227]"><div className="h-64 bg-[url('https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=90')] bg-cover bg-center" /><div className="grid grid-cols-3 gap-3 p-6 text-center"><div><p className="text-2xl font-semibold">Field</p><p className="mt-1 text-xs text-white/55">hands-on work</p></div><div><p className="text-2xl font-semibold">Local</p><p className="mt-1 text-xs text-white/55">relationships</p></div><div><p className="text-2xl font-semibold">Room</p><p className="mt-1 text-xs text-white/55">to grow</p></div></div></div></div></section>
    <section id="roles" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold tracking-[.18em] text-[#87964b] uppercase">Find your path</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.055em] sm:text-6xl">Pick the work that fits you.</h2></div><p className="max-w-md text-sm leading-6 text-[#62695f]">Each page explains the day-to-day, the opportunity, the standards, and how to apply.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2">{ROLES.map(({ href, label, kicker, title, copy, icon: Icon, image }) => <Link key={label} to={href} className="group overflow-hidden rounded-3xl bg-[#1d211d] text-white transition hover:-translate-y-1 hover:shadow-xl"><div className="grid md:grid-cols-[.8fr 1fr]"><div className="min-h-64 bg-cover bg-center transition duration-500 group-hover:scale-[1.02]" style={{ backgroundImage: `url(${image})` }} /><div className="flex flex-col justify-between p-7 sm:p-9"><div><div className="flex items-center justify-between"><span className="text-xs font-semibold tracking-[.16em] text-[#d5ec77] uppercase">{kicker}</span><Icon className="size-6 text-[#d5ec77]" /></div><h3 className="mt-7 text-3xl font-semibold leading-[1] tracking-[-.045em]">{title}</h3><p className="mt-4 text-sm leading-6 text-white/65">{copy}</p></div><span className="mt-8 flex items-center text-sm font-semibold text-[#d5ec77]">View {label} <ArrowUpRight className="ml-2 size-4" /></span></div></div></Link>)}</div></section>
    <section className="border-y border-[#1d211d]/10 bg-[#ece9e0]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:px-10 lg:py-28"><div><p className="text-xs font-semibold tracking-[.18em] text-[#87964b] uppercase">How it works</p><h2 className="mt-4 text-4xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl">Clear expectations from day one.</h2></div><div className="grid gap-8 sm:grid-cols-2">{PATH.map(([number, title, copy]) => <div key={number} className="border-t border-[#1d211d]/15 pt-5"><span className="text-sm font-semibold text-[#71803d]">{number}</span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#62695f]">{copy}</p></div>)}</div></div></section>
    <section className="border-y border-[#1d211d]/10 bg-[#f1f4e7]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-xs font-semibold tracking-[.18em] text-[#71803d] uppercase">The road to the life you want</p><h2 className="mt-4 text-4xl font-semibold leading-[.96] tracking-[-.055em] sm:text-6xl">Your vehicle can be a milestone — not a trap.</h2><p className="mt-6 text-lg leading-8 text-[#596357]">For field sales, the vehicle is often the office, the route, and part of the lifestyle. Build the business first, then choose the vehicle that the numbers can responsibly support.</p></div><div className="rounded-2xl bg-[#1d211d] p-7 text-white sm:p-8"><p className="text-xs font-semibold tracking-[.16em] text-[#d5ec77] uppercase">Illustrative career planning</p><p className="mt-4 text-2xl font-semibold">Sedan → F-150 → 2500 HD → dream vehicle</p><p className="mt-3 text-sm leading-6 text-white/70">This is a goal path, not a promise of income or financing approval. Always evaluate net profit, taxes, insurance, fuel, maintenance, depreciation, and reserves before upgrading.</p></div></div><div className="mt-12 flex snap-x gap-4 overflow-x-auto pb-4 [scrollbar-color:#71803d_transparent]">{VEHICLE_PATH.map(([stage, title, copy], index) => <article key={title} className="min-w-[270px] snap-start overflow-hidden rounded-2xl border border-[#1d211d]/10 bg-white sm:min-w-[310px]"><div className="h-48 bg-cover bg-center" style={{ backgroundImage: `url(${VEHICLE_IMAGES[index]})` }} /><div className="p-6"><p className="text-xs font-semibold tracking-[.14em] text-[#71803d] uppercase">{stage} · vehicle milestone</p><h3 className="mt-4 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#62695f]">{copy}</p></div></article>)}</div><p className="mt-7 text-xs leading-5 text-[#687265]">Vehicle photos are lifestyle references, not company-provided vehicles or earnings claims. Tax deductions vary by business structure, records, eligibility, and local law; speak with a qualified tax professional.</p></div></section>\n    <ExpertTopic compact />
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[#eaf0d0] p-7"><Users className="size-6 text-[#71803d]" /><h3 className="mt-10 text-xl font-semibold">People first</h3><p className="mt-2 text-sm leading-6 text-[#65705e]">Homeowners, crews, teammates, and referral partners all deserve clear communication.</p></div><div className="rounded-2xl bg-white p-7"><MapPin className="size-6 text-[#71803d]" /><h3 className="mt-10 text-xl font-semibold">Local opportunity</h3><p className="mt-2 text-sm leading-6 text-[#65705e]">Build relationships and a reputation in the communities you know best.</p></div><div className="rounded-2xl bg-[#1d211d] p-7 text-white"><Heart className="size-6 fill-[#d5ec77] text-[#d5ec77]" /><h3 className="mt-10 text-xl font-semibold">Built to last</h3><p className="mt-2 text-sm leading-6 text-white/70">We value the consistent details that turn one opportunity into a long-term book.</p></div></div></section>
    <section className="bg-[#d5ec77]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-5 py-16 sm:px-8 lg:flex-row lg:items-center lg:px-10"><div><p className="text-xs font-semibold tracking-[.18em] text-[#657035] uppercase">Not sure where you fit?</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Tell us what you do well. We'll help find the lane.</h2></div><a href="mailto:hello@lovemeafter.com?subject=LoveMeAfter career conversation" className="flex h-14 shrink-0 items-center justify-center rounded-full bg-[#1d211d] px-7 font-semibold text-white hover:bg-[#30382f]">Email the team <ArrowUpRight className="ml-2 size-5" /></a></div></section>
    <footer className="bg-[#182019] py-10 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 text-sm sm:flex-row sm:justify-between sm:px-8 lg:px-10"><Link to="/" className="flex items-center gap-2"><Heart className="size-4 fill-[#d5ec77] text-[#d5ec77]" /> LoveMeAfter</Link><span className="text-white/50">Careers · crews · community</span><a href="mailto:hello@lovemeafter.com" className="text-[#d5ec77]">hello@lovemeafter.com</a></div></footer>
  </main>;
}
