import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Check, Loader2, Phone, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { useNavigate } from "react-router";
import { toast } from "sonner";

const STATUSES = ["new", "reviewing", "approved", "declined"] as const;

export default function ContractorApplications() {
  const navigate = useNavigate();
  const applications = useQuery(api.ops.listContractorApplications);
  const updateStatus = useMutation(api.ops.updateContractorApplicationStatus);
  const [pending, setPending] = useState<Id<"contractorApplications"> | null>(null);
  const setStatus = async (id: Id<"contractorApplications">, status: typeof STATUSES[number]) => { setPending(id); try { await updateStatus({ id, status }); toast.success("Application updated"); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not update application"); } finally { setPending(null); } };
  return <main className="min-h-screen bg-[#f3f0e9] text-[#252523]"><header className="flex h-[76px] items-center justify-between border-b border-[#252523]/10 px-5 sm:px-8"><button onClick={() => navigate("/admin")} className="flex items-center gap-3 text-sm font-semibold tracking-[.14em] uppercase"><ArrowLeft className="size-4" /> Admin console</button><span className="flex items-center gap-2 text-xs text-[#6d6c67]"><ShieldCheck className="size-3.5 text-[#4f7a5c]" /> Contractor review</span></header><section className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><p className="text-[10px] font-semibold tracking-[.2em] text-[#9b6b50] uppercase">Partner applications</p><h1 className="mt-3 font-serif text-5xl tracking-[-.04em]">Contractor network</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#6d6c67]">Review new partner applications, check capacity and market fit, then move qualified crews into your onboarding process.</p><div className="mt-8 space-y-3">{applications === undefined ? <div className="flex justify-center py-24"><Loader2 className="size-5 animate-spin" /></div> : applications.length === 0 ? <div className="border border-dashed border-[#252523]/20 px-6 py-20 text-center"><p className="font-serif text-2xl">No applications yet.</p><p className="mt-2 text-sm text-[#6d6c67]">New contractor applications will appear here.</p></div> : applications.map((application) => <article key={application._id} className="border border-[#252523]/12 bg-[#ebe7de] p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-semibold">{application.company}</h2><span className="rounded-full bg-white/70 px-2.5 py-1 text-[10px] font-semibold tracking-[.12em] uppercase">{application.status}</span></div><p className="mt-2 text-sm">{application.name} · {application.trade} · {application.city}</p><p className="mt-2 flex items-center gap-2 text-xs text-[#6d6c67]"><Phone className="size-3.5" /> {application.phone} · {application.email}</p><p className="mt-3 text-xs text-[#6d6c67]">Capacity: {application.weeklyCapacity} installs/week</p>{application.notes && <p className="mt-3 max-w-2xl text-sm leading-6 text-[#6d6c67]">{application.notes}</p>}</div><div className="flex flex-wrap gap-2">{STATUSES.map((status) => <Button key={status} disabled={pending === application._id} onClick={() => setStatus(application._id, status)} variant={status === application.status ? "default" : "outline"} className="rounded-full text-xs capitalize"><>{status === "approved" ? <Check className="mr-1 size-3.5" /> : status === "declined" ? <X className="mr-1 size-3.5" /> : null}</>{status}</Button>)}</div></div></article>)}</div></section></main>;
}
