import { Button } from "@/components/ui/button";
import { ArrowLeft, ArrowUpRight, Check, ChevronRight, Fence, House, Paintbrush, Phone, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { useEffect } from "react";
import { Link, useNavigate } from "react-router";

const FEATURED_SERVICES = [
  { title: "Roofing", icon: House, image: "https://images.unsplash.com/photo-1632759145351-1d592919f522?auto=format&fit=crop&w=1400&q=90", copy: "Repair, replacement, ventilation, flashing, and storm-damage scopes with the details documented before work begins.", href: "/services/roofing" },
  { title: "Windows & doors", icon: Sparkles, image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=90", copy: "Comfort, curb appeal, security, and energy performance—measured correctly and installed with a clean finish.", href: "/services/windows" },
  { title: "Siding & exterior", icon: ShieldCheck, image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=90", copy: "A better outside envelope, from siding and trim to paint, masonry, fascia, and the details that make a home feel cared for.", href: "/services/siding" },
  { title: "Outdoor living", icon: Fence, image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1400&q=90", copy: "Decks, patios, fencing, drainage, landscaping, and the spaces that make the property work harder for your life.", href: "/services" },
];

const SERVICE_GROUPS = [
  { number: "01", title: "Exterior & protection", intro: "The work that protects your home from weather, water, wear, and time.", accent: "bg-[#eaf0d0]", services: ["Roofing repair & replacement", "Storm damage restoration", "Siding installation & repair", "Exterior painting", "Windows & skylights", "Exterior doors", "Garage doors", "Gutters & downspouts", "Fascia & soffit", "Chimneys & flashing", "Attic insulation", "Attic ventilation", "Weatherproofing & caulking"] },
  { number: "02", title: "Kitchens, baths & interiors", intro: "Thoughtful updates for the rooms where daily life happens.", accent: "bg-[#ece9e0]", services: ["Kitchen remodeling", "Bathroom remodeling", "Basement finishing", "Flooring installation", "Tile & backsplash", "Cabinetry", "Countertops", "Interior painting", "Drywall & texture", "Trim, molding & millwork", "Closets & storage", "Interior doors", "Demolition & haul-away"] },
  { number: "03", title: "Systems & comfort", intro: "Reliable home systems, coordinated with the same clear scope.", accent: "bg-[#e7eee8]", services: ["HVAC replacement & service", "Furnaces & heat pumps", "Air conditioning", "Water heaters", "Plumbing repair", "Electrical upgrades", "Lighting installation", "Panel & service upgrades", "Smart home systems", "Home backup power", "Indoor air quality", "Accessibility updates"] },
  { number: "04", title: "Outdoor spaces & property", intro: "Make the ground around your home safer, more useful, and more beautiful.", accent: "bg-[#e9e4d7]", services: ["Decks & porches", "Patios & hardscape", "Pergolas & shade structures", "Fencing & gates", "Driveways & walkways", "Concrete repair", "Masonry & retaining walls", "Landscaping", "Drainage & grading", "Outdoor lighting", "Irrigation", "Sheds & accessory structures", "Pool surrounds"] },
  { number: "05", title: "Specialty projects", intro: "The less-common projects that still deserve a clear plan and the right specialist.", accent: "bg-[#e4ebe5]", services: ["Solar coordination", "Insurance claim documentation", "Accessibility & aging-in-place", "Historic home updates", "Rental turnover refreshes", "Property management maintenance", "Multi-trade renovations", "Pre-sale improvement plans", "Punch lists & closeout work", "Emergency repair coordination"] },
] as const;

const PROJECT_IMAGES = [
  ["Roofline & protection", "https://images.unsplash.com/photo-1632759145351-1d592919f522?auto=format&fit=crop&w=1200&q=90"],
  ["Comfort & light", "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=90"],
  ["Outdoor living", "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=90"],
];

export default function Services() {
  const navigate = useNavigate();
  useEffect(() => { const previous = document.title; document.title = "All Home Improvement Services | LoveMeAfter"; return () => { document.title = previous; }; }, []);

  return (
    <main className="min-h-screen bg-[#f7f5f0] text-[#1d211d]">
      <header className="bg-[#182019] text-white"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><Link to="/" className="flex items-center gap-3 font-semibold"><span className="flex size-10 items-center justify-center rounded-full bg-[#d5ec77] text-[#1d211d]"><House className="size-5" /></span>LoveMeAfter</Link><div className="flex items-center gap-4"><a href="tel:+14244260760" className="hidden items-center gap-2 text-sm text-white/75 sm:flex"><Phone className="size-4" /> 424 426 0760</a><Button onClick={() => navigate("/")} variant="ghost" className="text-white hover:bg-white/10 hover:text-white"><ArrowLeft className="mr-2 size-4" /> Back home</Button></div></nav></header>

      <section className="relative overflow-hidden bg-[#182019] text-white"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(15,22,16,.97)_0%,rgba(15,22,16,.78)_48%,rgba(15,22,16,.25)_100%),url('https://images.unsplash.com/photo-1503387762-59230de8b0d6?auto=format&fit=crop&w=2400&q=90')] bg-cover bg-center" /><div className="relative mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-36"><p className="text-xs font-semibold tracking-[.2em] text-[#d5ec77] uppercase">One clear starting point</p><h1 className="mt-5 max-w-5xl text-5xl font-semibold leading-[.9] tracking-[-.07em] sm:text-7xl lg:text-[6.8rem]">Everything your home needs.<br /><span className="text-[#d5ec77]">Beautifully coordinated.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/75">LoveMeAfter is your first call for home improvement. We scope the project, coordinate the right specialist, and keep the experience clear from the first conversation to the final detail.</p><div className="mt-10 flex flex-wrap gap-3"><Button onClick={() => navigate("/")} className="h-14 rounded-full bg-[#d5ec77] px-7 text-base font-semibold text-[#1d211d] hover:bg-[#e1f895]">Start with a free estimate <ArrowUpRight className="ml-2 size-5" /></Button><a href="#catalog" className="flex h-14 items-center rounded-full border border-white/25 px-6 text-sm hover:bg-white/10">Explore the full catalog <ChevronRight className="ml-2 size-4" /></a></div></div></section>

      <section className="border-b border-[#1d211d]/10 bg-[#d5ec77]"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 sm:px-8 lg:grid-cols-3 lg:px-10"><div><p className="text-xs font-semibold tracking-[.16em] text-[#657035] uppercase">One conversation</p><p className="mt-2 text-2xl font-semibold tracking-[-.04em]">Start anywhere in the home.</p></div><div><p className="text-xs font-semibold tracking-[.16em] text-[#657035] uppercase">Many specialists</p><p className="mt-2 text-2xl font-semibold tracking-[-.04em]">The right crew for the scope.</p></div><div><p className="text-xs font-semibold tracking-[.16em] text-[#657035] uppercase">One standard</p><p className="mt-2 text-2xl font-semibold tracking-[-.04em]">Clear work, carefully finished.</p></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><p className="text-xs font-semibold tracking-[.18em] text-[#87964b] uppercase">Where we make the difference</p><h2 className="mt-4 max-w-md text-4xl font-semibold leading-[.96] tracking-[-.06em] sm:text-6xl">The big projects, made less complicated.</h2></div><p className="max-w-xl text-lg leading-8 text-[#62695f]">You do not need to know which trade to call first. Tell us what is not working, what you want to change, or what you want your home to feel like. We help turn that into a practical next step.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2">{FEATURED_SERVICES.map(({ title, icon: Icon, image, copy, href }) => <article key={title} className="group overflow-hidden border border-[#1d211d]/10 bg-white"><div className="h-64 bg-cover bg-center transition duration-500 group-hover:scale-[1.02]" style={{ backgroundImage: `url(${image})` }} /><div className="p-7"><div className="flex items-start justify-between gap-4"><div className="flex size-11 items-center justify-center rounded-xl bg-[#eaf0d0] text-[#71803d]"><Icon className="size-5" /></div><Link to={href} className="flex size-10 items-center justify-center rounded-full border border-[#1d211d]/10 text-[#71803d] hover:bg-[#eaf0d0]" aria-label={`Learn about ${title}`}><ArrowUpRight className="size-4" /></Link></div><h3 className="mt-8 text-2xl font-semibold tracking-[-.04em]">{title}</h3><p className="mt-3 max-w-lg text-base leading-7 text-[#62695f]">{copy}</p><div className="mt-6 flex items-center gap-2 text-xs font-semibold tracking-[.12em] text-[#71803d] uppercase">Written scope <Check className="size-4" /> Checked specialist</div></div></article>)}</div></section>

      <section id="catalog" className="border-y border-[#1d211d]/10 bg-[#ece9e0]"><div className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr] lg:items-end"><div><p className="text-xs font-semibold tracking-[.18em] text-[#87964b] uppercase">The complete catalog</p><h2 className="mt-4 max-w-md text-4xl font-semibold leading-[.96] tracking-[-.06em] sm:text-6xl">A lot of capability. A simple way in.</h2></div><p className="max-w-xl text-lg leading-8 text-[#62695f]">We organize the work by the way homeowners think about it: protect the exterior, improve the rooms, make the systems reliable, and use more of the property. If you do not see the exact wording for your project, ask us anyway.</p></div><div className="mt-14 space-y-3">{SERVICE_GROUPS.map((group) => <details key={group.number} open={group.number === "01"} className={`group border border-[#1d211d]/10 ${group.accent}`}><summary className="flex cursor-pointer list-none items-start justify-between gap-5 p-6 sm:p-8"><span className="flex gap-5 sm:gap-8"><span className="pt-1 text-sm font-semibold text-[#71803d]">{group.number}</span><span><span className="block text-2xl font-semibold tracking-[-.04em] sm:text-3xl">{group.title}</span><span className="mt-2 block max-w-xl text-sm leading-6 text-[#62695f]">{group.intro}</span></span></span><span className="mt-1 flex size-9 shrink-0 items-center justify-center rounded-full border border-[#1d211d]/15 transition group-open:rotate-90"><ChevronRight className="size-4" /></span></summary><div className="border-t border-[#1d211d]/10 px-6 pb-7 pt-6 sm:px-8"><div className="grid gap-x-8 gap-y-3 sm:grid-cols-2 lg:grid-cols-3">{group.services.map((service) => <div key={service} className="flex items-start gap-2 text-sm text-[#4f5a4d]"><Check className="mt-0.5 size-4 shrink-0 text-[#71803d]" />{service}</div>)}</div></div></details>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:px-10 lg:py-32"><div className="grid gap-4 md:grid-cols-3">{PROJECT_IMAGES.map(([title, image], index) => <div key={title} className={`group relative overflow-hidden ${index === 1 ? "md:mt-12" : ""}`}><div className="h-[420px] bg-cover bg-center transition duration-700 group-hover:scale-105" style={{ backgroundImage: `linear-gradient(0deg,rgba(15,22,16,.7),transparent 55%),url(${image})` }} /><div className="absolute inset-x-0 bottom-0 p-6 text-white"><p className="text-xs font-semibold tracking-[.16em] text-[#d5ec77] uppercase">0{index + 1} · LoveMeAfter</p><h3 className="mt-2 text-2xl font-semibold">{title}</h3></div></div>)}</div><div className="mt-16 grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-xs font-semibold tracking-[.18em] text-[#87964b] uppercase">How we keep it simple</p><h2 className="mt-4 text-4xl font-semibold leading-[.96] tracking-[-.06em] sm:text-6xl">You bring the question.<br />We bring the next step.</h2></div><div className="grid gap-4 sm:grid-cols-3">{[["01", "Describe", "Tell us what you see, feel, or want to change."], ["02", "Scope", "We coordinate the right inspection and specialist."], ["03", "Decide", "You get a written path forward, with no obligation."]].map(([number, title, copy]) => <div key={number} className="border-t-2 border-[#1d211d]/15 pt-5"><span className="text-sm font-semibold text-[#71803d]">{number}</span><h3 className="mt-4 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#62695f]">{copy}</p></div>)}</div></div></section>

      <section className="bg-[#1d211d] text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 px-5 py-20 sm:px-8 lg:flex-row lg:items-center lg:px-10 lg:py-24"><div><p className="text-xs font-semibold tracking-[.18em] text-[#d5ec77] uppercase">Not sure where to start?</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold leading-[.96] tracking-[-.06em] sm:text-6xl">You do not need to choose the trade.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-white/70">Give us the address, the concern, and the outcome you want. We will help organize the rest.</p></div><div className="flex flex-wrap gap-3"><Button onClick={() => navigate("/")} className="h-14 rounded-full bg-[#d5ec77] px-7 font-semibold text-[#1d211d] hover:bg-[#e1f895]">Get a free estimate <ArrowUpRight className="ml-2 size-5" /></Button><a href="tel:+14244260760" className="flex h-14 items-center rounded-full border border-white/25 px-6 text-sm font-semibold hover:bg-white/10"><Phone className="mr-2 size-4" /> 424 426 0760</a></div></div></section>

      <footer className="border-t border-[#1d211d]/10 bg-[#f7f5f0]"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-10 text-sm sm:px-8 lg:flex-row lg:items-center lg:justify-between lg:px-10"><Link to="/" className="flex items-center gap-3 font-semibold"><span className="flex size-8 items-center justify-center rounded-full bg-[#1d211d] text-[#d5ec77]"><House className="size-4" /></span>LoveMeAfter</Link><p className="text-[#62695f]">Home improvement, without the runaround.</p><Link to="/contractors" className="font-semibold text-[#71803d]">Work with us <ArrowUpRight className="ml-1 inline size-4" /></Link></div></footer>
    </main>
  );
}
