import { Button } from "@/components/ui/button";
import { ArrowLeft, ArrowUpRight, Check, Fence, House, Phone, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect } from "react";
import { useNavigate } from "react-router";

const SERVICE_DATA = [
  { title: "Roofing", icon: House, image: "https://images.unsplash.com/photo-1632759145351-1d592919f522?auto=format&fit=crop&w=1200&q=90", copy: "Repair, replacement, and storm-damage inspections with a written scope before you decide." },
  { title: "Siding", icon: ShieldCheck, image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=90", copy: "Refresh the outside envelope with durable siding, careful prep, and a clean final finish." },
  { title: "Windows", icon: Sparkles, image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=90", copy: "Improve comfort, curb appeal, and energy performance with correctly measured windows." },
  { title: "Gutters", icon: Fence, image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=90", copy: "Seamless drainage designed to move water away from your roofline and foundation." },
];

const BEFORE_AFTER = [
  { location: "Bay Area · coastal home", before: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1000&q=88", after: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=88", title: "Exterior refresh" },
  { location: "Colorado · storm-ready roofline", before: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=88", after: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=88", title: "Roof and siding update" },
  { location: "Missouri · family home", before: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=88", after: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=88", title: "Windows and curb appeal" },
];

export default function Services() {
  const navigate = useNavigate();
  useEffect(() => { const previous = document.title; document.title = "Home Improvement Services | LoveMeAfter"; return () => { document.title = previous; }; }, []);
  return (
    <main className="min-h-screen bg-[#f7f5f0] text-[#1d211d]">
      <header className="bg-[#182019] text-white"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><button onClick={() => navigate("/")} className="flex items-center gap-3 font-semibold"><span className="flex size-10 items-center justify-center rounded-full bg-[#d5ec77] text-[#1d211d]"><House className="size-5" /></span>LoveMeAfter</button><div className="flex items-center gap-4"><a href="tel:+14244260760" className="hidden items-center gap-2 text-sm text-white/75 sm:flex"><Phone className="size-4" /> 424 426 0760</a><Button onClick={() => navigate("/")} variant="ghost" className="text-white hover:bg-white/10 hover:text-white"><ArrowLeft className="mr-2 size-4" /> Back home</Button></div></nav></header>
      <section className="bg-[#182019] text-white"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><p className="text-xs font-semibold tracking-[.18em] text-[#d5ec77] uppercase">What we work on</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[.95] tracking-[-.06em] sm:text-7xl">The outside of your home, handled with care.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">From the first inspection to the last clean-up, LoveMeAfter brings clear scope, checked crews, and a real number to the conversation.</p></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-4 md:grid-cols-2">{SERVICE_DATA.map(({ title, icon: Icon, image, copy }) => <article key={title} className="overflow-hidden rounded-2xl border border-[#1d211d]/10 bg-white"><div className="h-64 bg-cover bg-center" style={{ backgroundImage: `url(${image})` }} /><div className="p-7"><div className="flex size-11 items-center justify-center rounded-xl bg-[#eaf0d0] text-[#71803d]"><Icon className="size-5" /></div><h2 className="mt-7 text-2xl font-semibold tracking-[-.04em]">{title}</h2><p className="mt-3 max-w-lg text-base leading-7 text-[#62695f]">{copy}</p><ul className="mt-6 space-y-2 text-sm text-[#4f5a4d]"><li className="flex gap-2"><Check className="mt-0.5 size-4 text-[#71803d]" /> Written scope before work starts</li><li className="flex gap-2"><Check className="mt-0.5 size-4 text-[#71803d]" /> Local requirements checked</li></ul></div></article>)}</div></section>
      <section className="border-y border-[#1d211d]/10 bg-[#ece9e0]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold tracking-[.18em] text-[#87964b] uppercase">Work in context</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.055em] sm:text-6xl">Before and after, without the guesswork.</h2></div><p className="max-w-md text-sm leading-6 text-[#62695f]">Example project imagery from active home improvement categories and markets. Every home, scope, and result is different.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{BEFORE_AFTER.map((project) => <article key={project.title} className="rounded-2xl bg-white p-3"><div className="grid grid-cols-2 gap-2"><div><div className="h-52 rounded-xl bg-cover bg-center" style={{ backgroundImage: `url(${project.before})` }} /><p className="mt-2 px-1 text-[10px] font-semibold tracking-[.15em] text-[#92998f] uppercase">Before</p></div><div><div className="h-52 rounded-xl bg-cover bg-center" style={{ backgroundImage: `url(${project.after})` }} /><p className="mt-2 px-1 text-[10px] font-semibold tracking-[.15em] text-[#71803d] uppercase">After</p></div></div><div className="px-2 pb-3 pt-5"><p className="text-xs font-semibold tracking-[.15em] text-[#87964b] uppercase">{project.location}</p><h3 className="mt-2 text-lg font-semibold">{project.title}</h3></div></article>)}</div></div></section>
      <section className="bg-[#d5ec77]"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-5 py-16 sm:px-8 lg:flex-row lg:items-center lg:px-10"><div><p className="text-xs font-semibold tracking-[.18em] text-[#657035] uppercase">See what your home needs</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Get the first number in writing.</h2></div><Button onClick={() => navigate("/")} className="h-14 rounded-full bg-[#1d211d] px-7 text-white hover:bg-[#30382f]">Request a free estimate <ArrowUpRight className="ml-2 size-5" /></Button></div></section>
    </main>
  );
}
