import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { ArrowLeft, BookOpen, BriefcaseBusiness, Check, ClipboardList, FileText, FolderKanban, Loader2, Plus, Rocket, Users } from "lucide-react";
import { useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { useNavigate } from "react-router";
import { toast } from "sonner";

type View = "overview" | "sops" | "projects" | "jobs";

const STATUS_LABELS = { planning: "Planning", active: "Active", on_hold: "On hold", complete: "Complete" } as const;

export default function Workspace() {
  const navigate = useNavigate();
  const [view, setView] = useState<View>("overview");
  const documents = useQuery(api.workspace.listDocuments);
  const projects = useQuery(api.workspace.listProjects);
  const jobPosts = useQuery(api.workspace.listJobPosts);
  const createDocument = useMutation(api.workspace.createDocument);
  const createProject = useMutation(api.workspace.createProject);
  const createJobPost = useMutation(api.workspace.createJobPost);
  const createTask = useMutation(api.workspace.createTask);
  const updateTaskStatus = useMutation(api.workspace.updateTaskStatus);
  const [saving, setSaving] = useState(false);

  const run = async (action: () => Promise<unknown>, success: string) => {
    setSaving(true);
    try { await action(); toast.success(success); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save"); } finally { setSaving(false); }
  };

  const loading = documents === undefined || projects === undefined || jobPosts === undefined;
  const allTasks = projects?.flatMap((project) => project.tasks) ?? [];

  return <main className="min-h-screen bg-[#f3f0e9] text-[#252523]">
    <header className="sticky top-0 z-20 flex h-[76px] items-center justify-between border-b border-[#252523]/10 bg-[#f3f0e9]/90 px-5 backdrop-blur-sm sm:px-8"><button onClick={() => navigate("/admin")} className="flex items-center gap-3 text-sm font-semibold tracking-[.14em] uppercase"><ArrowLeft className="size-4" /> Admin console</button><div className="flex items-center gap-2 text-xs text-[#6d6c67]"><BriefcaseBusiness className="size-4 text-[#9b6b50]" /> Internal workspace</div></header>
    <div className="mx-auto grid max-w-[1400px] lg:grid-cols-[240px_1fr]">
      <aside className="border-r border-[#252523]/10 px-6 py-10"><p className="text-[10px] font-semibold tracking-[.2em] text-[#9b9990] uppercase">Company workspace</p><nav className="mt-5 space-y-1">{([ ["overview", "Overview", Rocket], ["sops", "SOP library", BookOpen], ["projects", "Projects & tasks", FolderKanban], ["jobs", "Job posts", Users] ] as const).map(([id, label, Icon]) => <button key={id} onClick={() => setView(id)} className={`flex w-full items-center gap-3 rounded-sm px-3 py-2.5 text-left text-sm ${view === id ? "bg-[#e7e3d9] font-semibold" : "text-[#6d6c67] hover:text-[#252523]"}`}><Icon className="size-4" /> {label}</button>)}</nav><div className="mt-10 border-t border-[#252523]/10 pt-6 text-xs leading-6 text-[#9b9990]">Keep the operating system in one place: how work gets done, who owns it, and what happens next.</div></aside>
      <section className="min-w-0 px-5 py-10 sm:px-8 lg:px-12"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-semibold tracking-[.2em] text-[#9b6b50] uppercase">LoveMeAfter operations</p><h1 className="mt-3 font-serif text-5xl tracking-[-.04em]">{view === "overview" ? "Workspace" : view === "sops" ? "SOP library" : view === "projects" ? "Projects & tasks" : "Job posts"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#6d6c67]">{view === "overview" ? "The internal home for the playbooks, hiring, projects, and work that keeps the business moving." : view === "sops" ? "Write the repeatable way your team should handle intake, estimates, dispatch, quality, and closeout." : view === "projects" ? "Turn plans into owned tasks with a clear status and due date." : "Create and maintain recruiting posts for the roles that grow the operation."}</p></div><Button onClick={() => setView(view === "sops" ? "sops" : view === "jobs" ? "jobs" : "projects")} className="rounded-full bg-[#252523] text-[#f3f0e9] hover:bg-[#454541]"><Plus className="mr-2 size-4" /> Add {view === "sops" ? "SOP" : view === "jobs" ? "job post" : "project"}</Button></div>
        {loading ? <div className="flex justify-center py-32"><Loader2 className="size-5 animate-spin text-[#9b9990]" /></div> : view === "overview" ? <Overview documents={documents} projects={projects} jobPosts={jobPosts} tasks={allTasks} onView={setView} /> : view === "sops" ? <SopView documents={documents} saving={saving} onSave={(payload) => run(() => createDocument(payload), "SOP saved")} /> : view === "projects" ? <ProjectView projects={projects} saving={saving} onCreate={(payload) => run(() => createProject(payload), "Project created")} onTask={(payload) => run(() => createTask(payload), "Task added")} onTaskStatus={(id, status) => run(() => updateTaskStatus({ id, status }), "Task updated")} /> : <JobView jobPosts={jobPosts} saving={saving} onSave={(payload) => run(() => createJobPost(payload), "Job post created")} />}
      </section>
    </div>
  </main>;
}

function Overview({ documents, projects, jobPosts, tasks, onView }: { documents: NonNullable<ReturnType<typeof useQuery<typeof api.workspace.listDocuments>>>; projects: NonNullable<ReturnType<typeof useQuery<typeof api.workspace.listProjects>>>; jobPosts: NonNullable<ReturnType<typeof useQuery<typeof api.workspace.listJobPosts>>>; tasks: { status: string }[]; onView: (view: View) => void }) {
  const cards = [["SOPs", documents.length, "Repeatable playbooks", "sops", BookOpen], ["Projects", projects.length, "Active initiatives", "projects", FolderKanban], ["Open tasks", tasks.filter((task) => task.status !== "done").length, "Work to move forward", "projects", ClipboardList], ["Open job posts", jobPosts.filter((post) => post.status === "open").length, "Hiring opportunities", "jobs", Users]] as const;
  return <div className="mt-10"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, note, target, Icon]) => <button key={label} onClick={() => onView(target)} className="border border-[#252523]/12 bg-[#ebe7de] p-5 text-left transition hover:-translate-y-0.5 hover:shadow-[4px_4px_0_#d7d1c5]"><Icon className="size-5 text-[#9b6b50]" /><p className="mt-7 font-serif text-4xl">{value}</p><p className="mt-1 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-[#6d6c67]">{note}</p></button>)}</div><div className="mt-8 grid gap-4 lg:grid-cols-2"><div className="border border-[#252523]/12 bg-[#ebe7de] p-6"><p className="text-[10px] font-semibold tracking-[.18em] text-[#9b9990] uppercase">Suggested first SOPs</p><div className="mt-5 space-y-3 text-sm">{["Inbound lead response and qualification", "Estimate-to-contract handoff", "Crew verification and dispatch", "Project closeout and homeowner follow-up"].map((item) => <div key={item} className="flex items-center gap-3 border-t border-[#252523]/10 pt-3"><Check className="size-4 text-[#4f7a5c]" />{item}</div>)}</div></div><div className="border border-[#252523]/12 bg-[#252523] p-6 text-[#f3f0e9]"><p className="text-[10px] font-semibold tracking-[.18em] text-[#d5ec77] uppercase">Workspace principle</p><p className="mt-6 max-w-md font-serif text-3xl leading-tight">Make the next right action obvious.</p><p className="mt-4 text-sm leading-6 text-white/65">Every document, project, and task should help a teammate move from “what is this?” to “I know what to do next.”</p></div></div></div>;
}

function SopView({ documents, saving, onSave }: { documents: NonNullable<ReturnType<typeof useQuery<typeof api.workspace.listDocuments>>>; saving: boolean; onSave: (payload: { title: string; category: string; content: string; status: "draft" | "published" }) => void }) {
  const [title, setTitle] = useState(""); const [category, setCategory] = useState("Operations"); const [content, setContent] = useState(""); const [status, setStatus] = useState<"draft" | "published">("draft");
  return <div className="mt-10 grid gap-6 xl:grid-cols-[1fr_1.2fr]"><div className="border border-[#252523]/12 bg-[#ebe7de] p-6"><p className="text-[10px] font-semibold tracking-[.18em] text-[#9b9990] uppercase">Create an SOP</p><div className="mt-5 space-y-3"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Title, e.g. Lead qualification" className="h-11 w-full border border-[#252523]/15 bg-transparent px-3 text-sm outline-none" /><input value={category} onChange={(e) => setCategory(e.target.value)} placeholder="Category" className="h-11 w-full border border-[#252523]/15 bg-transparent px-3 text-sm outline-none" /><textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder="Write the procedure, checklist, owner, tools, and quality standard..." className="min-h-48 w-full border border-[#252523]/15 bg-transparent px-3 py-3 text-sm leading-6 outline-none" /><div className="flex gap-2"><Button onClick={() => onSave({ title, category, content, status })} disabled={saving || !title || !content} className="rounded-full bg-[#252523] text-[#f3f0e9]">{saving ? "Saving…" : "Save SOP"}</Button><Button type="button" variant="outline" onClick={() => setStatus(status === "draft" ? "published" : "draft")} className="rounded-full">{status === "draft" ? "Save as draft" : "Publish"}</Button></div></div></div><div className="space-y-3">{documents.length === 0 ? <Empty label="No SOPs yet" text="Start with the operating procedures your team repeats every week." /> : documents.map((document) => <article key={document._id} className="border border-[#252523]/12 bg-[#ebe7de] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold tracking-[.16em] text-[#9b6b50] uppercase">{document.category} · {document.status}</p><h2 className="mt-2 font-serif text-2xl">{document.title}</h2></div><FileText className="size-5 text-[#9b9990]" /></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[#6d6c67]">{document.content}</p></article>)}</div></div>;
}

function ProjectView({ projects, saving, onCreate, onTask, onTaskStatus }: { projects: NonNullable<ReturnType<typeof useQuery<typeof api.workspace.listProjects>>>; saving: boolean; onCreate: (payload: { name: string; description: string; status: "planning" | "active" | "on_hold" | "complete" }) => void; onTask: (payload: { projectId: Id<"workspaceProjects">; title: string; status: "todo" }) => void; onTaskStatus: (id: Id<"workspaceTasks">, status: "todo" | "in_progress" | "done") => void }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState("");
  return <div className="mt-10"><div className="grid gap-3 md:grid-cols-3">{projects.map((project) => <article key={project._id} className="border border-[#252523]/12 bg-[#ebe7de] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold tracking-[.16em] text-[#9b6b50] uppercase">{STATUS_LABELS[project.status]}</p><h2 className="mt-2 font-serif text-2xl">{project.name}</h2></div><FolderKanban className="size-5 text-[#9b9990]" /></div><p className="mt-3 text-sm leading-6 text-[#6d6c67]">{project.description}</p><div className="mt-5 space-y-2 border-t border-[#252523]/10 pt-4">{project.tasks.map((task) => <button key={task._id} onClick={() => onTaskStatus(task._id, task.status === "todo" ? "in_progress" : task.status === "in_progress" ? "done" : "todo")} className="flex w-full items-center gap-2 text-left text-xs"><span className={`size-3 rounded-full border ${task.status === "done" ? "border-[#4f7a5c] bg-[#4f7a5c]" : task.status === "in_progress" ? "border-[#c39a5f] bg-[#c39a5f]" : "border-[#9b9990]"}`} />{task.title}</button>)}<input placeholder="Add a task and press Enter" className="mt-2 h-9 w-full border-b border-[#252523]/15 bg-transparent text-xs outline-none" onKeyDown={(e) => { if (e.key === "Enter" && e.currentTarget.value.trim()) { onTask({ projectId: project._id, title: e.currentTarget.value.trim(), status: "todo" }); e.currentTarget.value = ""; } }} /></div></article>)}{projects.length === 0 && <Empty label="No projects yet" text="Create the first project to give the team a shared destination." />}</div><div className="mt-8 max-w-xl border border-[#252523]/12 bg-[#ebe7de] p-6"><p className="text-[10px] font-semibold tracking-[.18em] text-[#9b9990] uppercase">New project</p><div className="mt-4 space-y-3"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Project name" className="h-11 w-full border border-[#252523]/15 bg-transparent px-3 text-sm outline-none" /><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="What does done look like?" className="min-h-24 w-full border border-[#252523]/15 bg-transparent px-3 py-3 text-sm outline-none" /><Button onClick={() => { onCreate({ name, description, status: "planning" }); setName(""); setDescription(""); }} disabled={saving || !name || !description} className="rounded-full bg-[#252523] text-[#f3f0e9]">Create project</Button></div></div></div>;
}

function JobView({ jobPosts, saving, onSave }: { jobPosts: NonNullable<ReturnType<typeof useQuery<typeof api.workspace.listJobPosts>>>; saving: boolean; onSave: (payload: { title: string; department: string; location: string; description: string; compensation: string; status: "draft" | "open" | "closed" }) => void }) {
  const [title, setTitle] = useState(""); const [department, setDepartment] = useState("Operations"); const [location, setLocation] = useState("Remote"); const [description, setDescription] = useState(""); const [compensation, setCompensation] = useState("");
  return <div className="mt-10 grid gap-6 xl:grid-cols-[1fr_1.2fr]"><div className="border border-[#252523]/12 bg-[#ebe7de] p-6"><p className="text-[10px] font-semibold tracking-[.18em] text-[#9b9990] uppercase">Create a job post</p><div className="mt-5 space-y-3"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Role title" className="h-11 w-full border border-[#252523]/15 bg-transparent px-3 text-sm outline-none" /><div className="grid gap-3 sm:grid-cols-2"><input value={department} onChange={(e) => setDepartment(e.target.value)} placeholder="Department" className="h-11 w-full border border-[#252523]/15 bg-transparent px-3 text-sm outline-none" /><input value={location} onChange={(e) => setLocation(e.target.value)} placeholder="Location" className="h-11 w-full border border-[#252523]/15 bg-transparent px-3 text-sm outline-none" /></div><input value={compensation} onChange={(e) => setCompensation(e.target.value)} placeholder="Compensation range or description" className="h-11 w-full border border-[#252523]/15 bg-transparent px-3 text-sm outline-none" /><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Responsibilities, qualifications, and how to apply" className="min-h-40 w-full border border-[#252523]/15 bg-transparent px-3 py-3 text-sm leading-6 outline-none" /><Button onClick={() => onSave({ title, department, location, description, compensation, status: "draft" })} disabled={saving || !title || !description} className="rounded-full bg-[#252523] text-[#f3f0e9]">Save job post</Button></div></div><div className="space-y-3">{jobPosts.length === 0 ? <Empty label="No job posts yet" text="Create a draft, then review it before publishing it publicly." /> : jobPosts.map((post) => <article key={post._id} className="border border-[#252523]/12 bg-[#ebe7de] p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold tracking-[.16em] text-[#9b6b50] uppercase">{post.department} · {post.location} · {post.status}</p><h2 className="mt-2 font-serif text-2xl">{post.title}</h2></div><BriefcaseBusiness className="size-5 text-[#9b9990]" /></div><p className="mt-3 text-sm font-medium">{post.compensation || "Compensation discussed during application"}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#6d6c67]">{post.description}</p></article>)}</div></div>;
}

function Empty({ label, text }: { label: string; text: string }) { return <div className="border border-dashed border-[#252523]/20 px-6 py-20 text-center"><p className="font-serif text-2xl">{label}</p><p className="mt-2 text-sm text-[#6d6c67]">{text}</p></div>; }
