import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createFirestoreRecord, updateFirestoreRecord, useFirestoreCollection } from "@/lib/firestore-data";
import { ArrowLeft, BookOpen, BriefcaseBusiness, Check, FolderKanban, Loader2, Plus, Users } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router";
import { toast } from "sonner";

type View = "overview" | "sops" | "projects" | "jobs";
type Doc = { id: string; title: string; category: string; content: string; status: string };
type Project = { id: string; name: string; description: string; status: string };
type Task = { id: string; projectId: string; title: string; status: string };
type JobPost = { id: string; title: string; department: string; location: string; description: string; compensation: string; status: string };

export default function Workspace() {
  const navigate = useNavigate();
  const [view, setView] = useState<View>("overview");
  const documents = useFirestoreCollection<Doc>("workspaceDocuments").records;
  const projects = useFirestoreCollection<Project>("workspaceProjects").records;
  const tasks = useFirestoreCollection<Task>("workspaceTasks").records;
  const jobPosts = useFirestoreCollection<JobPost>("workspaceJobPosts").records;
  const [saving, setSaving] = useState(false);

  async function save(collectionName: string, data: Record<string, unknown>, message: string) {
    setSaving(true);
    try { await createFirestoreRecord(collectionName, data); toast.success(message); } catch (value) { toast.error(value instanceof Error ? value.message : "Could not save"); } finally { setSaving(false); }
  }

  return <main className="min-h-screen bg-[#f3f0e9] text-[#252523]"><header className="sticky top-0 z-20 flex h-[76px] items-center justify-between border-b border-[#252523]/10 bg-[#f3f0e9]/90 px-5 backdrop-blur-sm sm:px-8"><button onClick={() => navigate("/admin")} className="flex items-center gap-3 text-sm font-semibold tracking-[.14em] uppercase"><ArrowLeft className="size-4" /> Admin console</button><span className="flex items-center gap-2 text-xs text-[#6d6c67]"><BriefcaseBusiness className="size-4 text-[#9b6b50]" /> Internal workspace</span></header><div className="mx-auto grid max-w-[1400px] lg:grid-cols-[240px_1fr]"><aside className="border-r border-[#252523]/10 px-6 py-10"><p className="text-[10px] font-semibold tracking-[.2em] text-[#9b9990] uppercase">Company workspace</p><nav className="mt-5 space-y-1">{([["overview", "Overview", BriefcaseBusiness], ["sops", "SOP library", BookOpen], ["projects", "Projects & tasks", FolderKanban], ["jobs", "Job posts", Users]] as const).map(([id, label, Icon]) => <button key={id} onClick={() => setView(id)} className={`flex w-full items-center gap-3 rounded-sm px-3 py-2.5 text-left text-sm ${view === id ? "bg-[#e7e3d9] font-semibold" : "text-[#6d6c67]"}`}><Icon className="size-4" /> {label}</button>)}</nav></aside><section className="min-w-0 px-5 py-10 sm:px-8 lg:px-12"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-semibold tracking-[.2em] text-[#9b6b50] uppercase">LoveMeAfter operations</p><h1 className="mt-3 font-serif text-5xl tracking-[-.04em]">{view === "overview" ? "Workspace" : view === "sops" ? "SOP library" : view === "projects" ? "Projects & tasks" : "Job posts"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#6d6c67]">Keep the operating system in one place: how work gets done, who owns it, and what happens next.</p></div><Button onClick={() => setView(view === "sops" ? "sops" : view === "jobs" ? "jobs" : "projects")} className="rounded-full bg-[#252523] text-[#f3f0e9]"><Plus className="mr-2 size-4" /> Add item</Button></div>{view === "overview" && <Overview documents={documents} projects={projects} tasks={tasks} jobs={jobPosts} onView={setView} />}{view === "sops" && <Sops documents={documents} saving={saving} onSave={(data) => save("workspaceDocuments", data, "SOP saved")} />}{view === "projects" && <Projects projects={projects} tasks={tasks} saving={saving} onProject={(data) => save("workspaceProjects", data, "Project created")} onTask={(data) => save("workspaceTasks", data, "Task added")} onTaskStatus={(id, status) => updateFirestoreRecord("workspaceTasks", id, { status })} />}{view === "jobs" && <Jobs posts={jobPosts} saving={saving} onSave={(data) => save("workspaceJobPosts", data, "Job post saved")} />}</section></div></main>;
}
function Overview({ documents, projects, tasks, jobs, onView }: { documents: Doc[]; projects: Project[]; tasks: Task[]; jobs: JobPost[]; onView: (view: View) => void }) { const cards = [["SOPs", documents.length, "sops", BookOpen], ["Projects", projects.length, "projects", FolderKanban], ["Open tasks", tasks.filter((task) => task.status !== "done").length, "projects", Check], ["Job posts", jobs.length, "jobs", Users]] as const; return <div className="mt-10"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, target, Icon]) => <button key={label} onClick={() => onView(target)} className="border border-[#252523]/12 bg-[#ebe7de] p-5 text-left"><Icon className="size-5 text-[#9b6b50]" /><p className="mt-7 font-serif text-4xl">{value}</p><p className="mt-1 text-sm font-semibold">{label}</p></button>)}</div></div>; }
function Sops({ documents, saving, onSave }: { documents: Doc[]; saving: boolean; onSave: (data: Record<string, unknown>) => void }) { const [title, setTitle] = useState(""); const [content, setContent] = useState(""); return <div className="mt-10 grid gap-6 xl:grid-cols-[1fr_1.2fr]"><div className="border border-[#252523]/12 bg-[#ebe7de] p-6"><p className="text-[10px] font-semibold tracking-[.18em] text-[#9b9990] uppercase">Create an SOP</p><div className="mt-5 space-y-3"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Title" /><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Procedure, owner, tools, and quality standard..." className="min-h-48 w-full border border-[#252523]/15 bg-transparent px-3 py-3 text-sm outline-none" /><Button disabled={saving || !title || !content} onClick={() => { onSave({ title, content, category: "Operations", status: "draft" }); setTitle(""); setContent(""); }} className="rounded-full bg-[#252523] text-white">{saving ? <Loader2 className="size-4 animate-spin" /> : "Save SOP"}</Button></div></div><div className="space-y-3">{documents.map((document) => <article key={document.id} className="border border-[#252523]/12 bg-[#ebe7de] p-5"><p className="text-[10px] font-semibold tracking-[.16em] text-[#9b6b50] uppercase">{document.category} · {document.status}</p><h2 className="mt-2 font-serif text-2xl">{document.title}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-[#6d6c67]">{document.content}</p></article>)}</div></div>; }
function Projects({ projects, tasks, saving, onProject, onTask, onTaskStatus }: { projects: Project[]; tasks: Task[]; saving: boolean; onProject: (data: Record<string, unknown>) => void; onTask: (data: Record<string, unknown>) => void; onTaskStatus: (id: string, status: string) => void }) { const [name, setName] = useState(""); const [description, setDescription] = useState(""); return <div className="mt-10"><div className="grid gap-3 md:grid-cols-3">{projects.map((project) => <article key={project.id} className="border border-[#252523]/12 bg-[#ebe7de] p-5"><p className="text-[10px] font-semibold tracking-[.16em] text-[#9b6b50] uppercase">{project.status}</p><h2 className="mt-2 font-serif text-2xl">{project.name}</h2><p className="mt-3 text-sm text-[#6d6c67]">{project.description}</p><div className="mt-5 space-y-2 border-t border-[#252523]/10 pt-4">{tasks.filter((task) => task.projectId === project.id).map((task) => <button key={task.id} onClick={() => onTaskStatus(task.id, task.status === "todo" ? "in_progress" : task.status === "in_progress" ? "done" : "todo")} className="flex w-full gap-2 text-left text-xs"><span className={`size-3 rounded-full border ${task.status === "done" ? "bg-[#4f7a5c]" : "border-[#9b9990]"}`} />{task.title}</button>)}<input placeholder="Add task + Enter" className="mt-2 h-9 w-full border-b border-[#252523]/15 bg-transparent text-xs outline-none" onKeyDown={(event) => { if (event.key === "Enter" && event.currentTarget.value.trim()) { onTask({ projectId: project.id, title: event.currentTarget.value.trim(), status: "todo" }); event.currentTarget.value = ""; } }} /></div></article>)}</div><div className="mt-8 max-w-xl space-y-3 border border-[#252523]/12 bg-[#ebe7de] p-6"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Project name" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="What does done look like?" className="min-h-24 w-full border border-[#252523]/15 bg-transparent px-3 py-3 text-sm outline-none" /><Button disabled={saving || !name || !description} onClick={() => { onProject({ name, description, status: "planning" }); setName(""); setDescription(""); }} className="rounded-full bg-[#252523] text-white">Create project</Button></div></div>; }
function Jobs({ posts, saving, onSave }: { posts: JobPost[]; saving: boolean; onSave: (data: Record<string, unknown>) => void }) { const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); return <div className="mt-10 grid gap-6 xl:grid-cols-[1fr_1.2fr]"><div className="space-y-3 border border-[#252523]/12 bg-[#ebe7de] p-6"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Role title" /><Input defaultValue="Operations" placeholder="Department" id="department" /><Input defaultValue="Remote" placeholder="Location" id="location" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Responsibilities and qualifications" className="min-h-40 w-full border border-[#252523]/15 bg-transparent px-3 py-3 text-sm outline-none" /><Button disabled={saving || !title || !description} onClick={() => { onSave({ title, description, department: "Operations", location: "Remote", compensation: "Discussed during application", status: "draft" }); setTitle(""); setDescription(""); }} className="rounded-full bg-[#252523] text-white">Save job post</Button></div><div className="space-y-3">{posts.map((post) => <article key={post.id} className="border border-[#252523]/12 bg-[#ebe7de] p-5"><p className="text-[10px] font-semibold tracking-[.16em] text-[#9b6b50] uppercase">{post.department} · {post.location} · {post.status}</p><h2 className="mt-2 font-serif text-2xl">{post.title}</h2><p className="mt-3 whitespace-pre-wrap text-sm text-[#6d6c67]">{post.description}</p></article>)}</div></div>; }
